#====================================================================================================
#
#         XY-RandomSell KotlinEdition ConfigurationFile
#         随机收购 · 配置文件
#         Author | 作者: Mu_Cloud
#
#====================================================================================================
version: "StarrySky_C1.0" #         !!! version 项禁止修改，对随意修改造成设置丢失的后果自负 !!!

#====================================================================================================
#
#         !!! GUIMode 只控制样式，样式案例不等于行数，GUIRow 用于调节行数 !!!
#         GUIMode 1 -> #########        GUIMode 2 -> XXXXXXXXX
#                      #########                     X#######X
#                      #########                     X#######X
#                      X<XXXXX>X                     x<XXXXX>X
#
#         GUIRow 仅允许选择 3 4 5 6
#         GUITitle 支持颜色字符和变量
#====================================================================================================
GUIMode: 1
GUIRow: 6
GUITitle: "&6随机收购"

#====================================================================================================
#   Prefix 项用于设置带前缀的消息的前缀
#====================================================================================================
Prefix: "&7&l[&6&lXY&7&l-&e&lRandomSell&7&l] &b&l>>> "

#====================================================================================================
#   商店设置
#   Refresh 用于控制商店的可刷新性, 接收一个数, 作为商店刷新的分钟数, 不可为负数
#   Capacity 用于控制随机挑选出来的项目数量, 该数量应尽量小于该商店声明的商品项, 否则可能出现错误
#====================================================================================================
Refresh: 5
Capacity: 5

#====================================================================================================
#   商品详细
#====================================================================================================
Productions:
    - material: "IRON" # 商品的原物品, 需要输入 命名空间ID (必须大写), 详见 https://wiki.biligame.com/mc/Java%E7%89%88%E6%95%B0%E6%8D%AE%E5%80%BC 中物品, 实体
      name: "商品显示名"
      lore: ["商品的描述"]
      price: 0.8 # 收购价，不可为负数
      amount: 20 # 最大收购数量, 不可为负数