#==================================================
name: XY-RandomSell
main: me.mucloud.plugin.XY.RandomSell.Main
version: "StarrySky"
versionCN: "星空"
versionInternal: 1.1103
author: "Mu_Cloud"
#==================================================
api-version: 1.13
softdepend: ["PlaceholderAPI"]
description: XY-RandomSell Plugin.
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.21
  - org.jetbrains.kotlin:kotlin-stdlib-common:1.8.21
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21
  - org.jetbrains:annotations:23.0.0

commands:
  xyrs:
    usage: /xyrs [args]
    description: "This plugin is not compatible in your server when you look this message."

permissions:
  xyrsp.gui:
    default: true
  xyrsp.refresh:
    default: op
  xyrsp.control:
    default: op
  xyrsp.version:
    default: op